name: Build and Release Go Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod tidy

    - name: Build the Go application
      run: go build -o docker-compose-exec 

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-exec 
        path: docker-compose-exec 

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-compose-exec 

    - name: Generate Release Tag
      id: generate_tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d-%H%M%S')-$(git rev-parse --short HEAD)"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "Generated tag: $TAG_NAME"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./docker-compose-exec 
        asset_name: docker-compose-exec 
        asset_content_type: application/octet-stream
